# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bada284480fca2bf568e6f56578e51f03371d75ed9a60d97809ab88b7b91b6fe7e4cdba28a765f6ac2dd10c8f556223e38052d16f1c098eafed5b155c39a49bb

test:
  secret_key_base: 0ff563b87436149434d8f5a7653720e234aaee16c548beac511aaf769f35902fad1404a16bb7b416c99e5190d17242e7ca241b3b600d0ffe56c2f612cf9940bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
